# BOF
# Add 'repo' label to any root file changes
repo:
- '*'
# 
git:
- any: ['**/.gitignore']
#
workflow:
- any: ['.github/**/*']
#
project:
- any: ['terraform/.terraformrc']
#
code:
- any: ['terraform/**/*']
#
documentation:
- any: ['**/*.md']

...
# EOF